package com.example.zhh.pojo;

import java.io.Serializable;

public class QuestionDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_detail.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_detail.difficult_level
     *
     * @mbggenerated
     */
    private String difficultLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_detail.id
     *
     * @return the value of question_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_detail.id
     *
     * @param id the value for question_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_detail.question_id
     *
     * @return the value of question_detail.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_detail.question_id
     *
     * @param questionId the value for question_detail.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_detail.difficult_level
     *
     * @return the value of question_detail.difficult_level
     *
     * @mbggenerated
     */
    public String getDifficultLevel() {
        return difficultLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_detail.difficult_level
     *
     * @param difficultLevel the value for question_detail.difficult_level
     *
     * @mbggenerated
     */
    public void setDifficultLevel(String difficultLevel) {
        this.difficultLevel = difficultLevel == null ? null : difficultLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", questionId=").append(questionId);
        sb.append(", difficultLevel=").append(difficultLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}