package com.example.zhh.pojo;

import java.io.Serializable;

public class UserProfile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.university
     *
     * @mbggenerated
     */
    private String university;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gpa
     *
     * @mbggenerated
     */
    private Float gpa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.active_days_within_30
     *
     * @mbggenerated
     */
    private Integer activeDaysWithin30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.question_cnt
     *
     * @mbggenerated
     */
    private Integer questionCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.answer_cnt
     *
     * @mbggenerated
     */
    private Integer answerCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.id
     *
     * @return the value of user_profile.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.id
     *
     * @param id the value for user_profile.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.device_id
     *
     * @return the value of user_profile.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.device_id
     *
     * @param deviceId the value for user_profile.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.age
     *
     * @return the value of user_profile.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.age
     *
     * @param age the value for user_profile.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.university
     *
     * @return the value of user_profile.university
     *
     * @mbggenerated
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.university
     *
     * @param university the value for user_profile.university
     *
     * @mbggenerated
     */
    public void setUniversity(String university) {
        this.university = university == null ? null : university.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gpa
     *
     * @return the value of user_profile.gpa
     *
     * @mbggenerated
     */
    public Float getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gpa
     *
     * @param gpa the value for user_profile.gpa
     *
     * @mbggenerated
     */
    public void setGpa(Float gpa) {
        this.gpa = gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.active_days_within_30
     *
     * @return the value of user_profile.active_days_within_30
     *
     * @mbggenerated
     */
    public Integer getActiveDaysWithin30() {
        return activeDaysWithin30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.active_days_within_30
     *
     * @param activeDaysWithin30 the value for user_profile.active_days_within_30
     *
     * @mbggenerated
     */
    public void setActiveDaysWithin30(Integer activeDaysWithin30) {
        this.activeDaysWithin30 = activeDaysWithin30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.question_cnt
     *
     * @return the value of user_profile.question_cnt
     *
     * @mbggenerated
     */
    public Integer getQuestionCnt() {
        return questionCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.question_cnt
     *
     * @param questionCnt the value for user_profile.question_cnt
     *
     * @mbggenerated
     */
    public void setQuestionCnt(Integer questionCnt) {
        this.questionCnt = questionCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.answer_cnt
     *
     * @return the value of user_profile.answer_cnt
     *
     * @mbggenerated
     */
    public Integer getAnswerCnt() {
        return answerCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.answer_cnt
     *
     * @param answerCnt the value for user_profile.answer_cnt
     *
     * @mbggenerated
     */
    public void setAnswerCnt(Integer answerCnt) {
        this.answerCnt = answerCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", gender=").append(gender);
        sb.append(", age=").append(age);
        sb.append(", university=").append(university);
        sb.append(", gpa=").append(gpa);
        sb.append(", activeDaysWithin30=").append(activeDaysWithin30);
        sb.append(", questionCnt=").append(questionCnt);
        sb.append(", answerCnt=").append(answerCnt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}