package com.example.zhh.dao;

import com.example.zhh.pojo.TTaishi;
import com.example.zhh.pojo.TTaishiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface TTaishiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int countByExample(TTaishiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int deleteByExample(TTaishiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int insert(TTaishi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int insertSelective(TTaishi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    List<TTaishi> selectByExample(TTaishiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    TTaishi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TTaishi record, @Param("example") TTaishiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TTaishi record, @Param("example") TTaishiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TTaishi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taishi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TTaishi record);
}