package com.example.zhh.dao;

import com.example.zhh.pojo.UserProfile;
import com.example.zhh.pojo.UserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int countByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int deleteByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    List<UserProfile> selectByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);
}